<?php
// Register Custom Taxonomy Type CurrentAffair
// Taxonomy Type Key: countries
// Register Taxonomy: Countries

function create_countries_tax() {

    $labels = array(
        'name'              => _x( 'Countries', 'taxonomy general name', 'wpbrsmedia' ),
        'singular_name'     => _x( 'Country', 'taxonomy singular name', 'wpbrsmedia' ),
        'search_items'      => __( 'Search Countries', 'wpbrsmedia' ),
        'all_items'         => __( 'All Countries', 'wpbrsmedia' ),
        'parent_item'       => __( 'Parent Country', 'wpbrsmedia' ),
        'parent_item_colon' => __( 'Parent Country:', 'wpbrsmedia' ),
        'edit_item'         => __( 'Edit Country', 'wpbrsmedia' ),
        'update_item'       => __( 'Update Country', 'wpbrsmedia' ),
        'add_new_item'      => __( 'Add New Country', 'wpbrsmedia' ),
        'new_item_name'     => __( 'New Country Name', 'wpbrsmedia' ),
        'menu_name'         => __( 'Country', 'wpbrsmedia' ),
    );

    $args = array(
        'labels' => $labels,
        'description' => __( 'Countries around the world.', 'wpbrsmedia' ),
        'hierarchical' => true,
        'public' => true,
        'publicly_queryable' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_nav_menus' => true,
        'show_tagcloud' => true,
        'show_in_quick_edit' => true,
        'show_admin_column' => true,
        'show_in_rest' => true,
        'query_var' => true,
        'rewrite' => array( 'slug' => 'countries' ),
    );

    register_taxonomy(
        'country',
        array( 'currentaffair', 'stateprofile', 'cityprofile', 'naturalfood', 'indiatourism', 'govtprogram', 'education', 'leader', 'infrastructure', 'business' ),
        $args
    );
}
add_action( 'init', 'create_countries_tax' );


function add_countries_with_descriptions() {
    $countries = array(
        'World Wide' => 'The global community encompassing all countries.',
        'Afghanistan' => 'Afghanistan is a landlocked country located in South Asia.',
        'Albania' => 'Albania is a country in Southeast Europe on the Adriatic and Ionian Sea.',
        'Algeria' => 'Algeria is a country in North Africa, the largest in the Arab world.',
        'Andorra' => 'Andorra is a small country in the Pyrenees mountains between France and Spain.',
        'Angola' => 'Angola is a country on the west coast of Southern Africa.',
        'Antigua and Barbuda' => 'Antigua and Barbuda is a twin-island nation in the Caribbean.',
        'Argentina' => 'Argentina is a country in South America known for its rich culture and history.',
        'Armenia' => 'Armenia is a landlocked country in the South Caucasus region of Eurasia.',
        'Australia' => 'Australia is a country and continent surrounded by the Indian and Pacific oceans.',
        'Austria' => 'Austria is a landlocked country in Central Europe.',
        'Azerbaijan' => 'Azerbaijan is a country in the South Caucasus region of Eurasia.',
        'Bahamas' => 'The Bahamas is an archipelago in the Caribbean Sea and Atlantic Ocean.',
        'Bahrain' => 'Bahrain is a small island country in the Persian Gulf.',
        'Bangladesh' => 'Bangladesh is a country in South Asia, bordered by India and Myanmar.',
        'Barbados' => 'Barbados is an island country in the Caribbean Sea.',
        'Belarus' => 'Belarus is a landlocked country in Eastern Europe.',
        'Belgium' => 'Belgium is a country in Western Europe known for its medieval towns and Renaissance architecture.',
        'Belize' => 'Belize is a country on the eastern coast of Central America.',
        'Benin' => 'Benin is a country in West Africa, known for its rich cultural heritage.',
        'Bhutan' => 'Bhutan is a landlocked country in the Eastern Himalayas.',
        'Bolivia' => 'Bolivia is a landlocked country in the heart of South America.',
        'Bosnia and Herzegovina' => 'Bosnia and Herzegovina is a country in Southeastern Europe on the Balkan Peninsula.',
        'Botswana' => 'Botswana is a landlocked country in Southern Africa.',
        'Brazil' => 'Brazil is the largest country in South America, known for its rainforests and cultural diversity.',
        'Brunei' => 'Brunei is a small, rich country on the island of Borneo in Southeast Asia.',
        'Bulgaria' => 'Bulgaria is a country in Southeast Europe, known for its diverse landscapes and history.',
        'Burkina Faso' => 'Burkina Faso is a landlocked country in West Africa.',
        'Burundi' => 'Burundi is a landlocked country in East Africa, known for its lakes and hilly terrain.',
        'Cabo Verde' => 'Cabo Verde is an island country in the central Atlantic Ocean.',
        'Cambodia' => 'Cambodia is a country in Southeast Asia known for its Angkor Wat temple complex.',
        'Cameroon' => 'Cameroon is a country in Central Africa known for its diversity of cultures and languages.',
        'Canada' => 'Canada is the second-largest country in the world by land area, located in North America.',
        'Central African Republic' => 'The Central African Republic is a landlocked country in Central Africa.',
        'Chad' => 'Chad is a landlocked country in north-central Africa.',
        'Chile' => 'Chile is a narrow strip of land in South America, stretching along the Pacific Ocean.',
        'China' => 'China is the most populous country in the world, located in East Asia.',
        'Colombia' => 'Colombia is a country in South America known for its coffee and vibrant culture.',
        'Comoros' => 'The Comoros is an island nation in the Indian Ocean, located between Madagascar and Mozambique.',
        'Congo (Congo-Brazzaville)' => 'The Republic of the Congo is a country in Central Africa.',
        'Congo (Democratic Republic)' => 'The Democratic Republic of the Congo is a large country in Central Africa.',
        'Costa Rica' => 'Costa Rica is a small country in Central America known for its biodiversity and eco-tourism.',
        'Croatia' => 'Croatia is a country in Southeast Europe on the Adriatic Sea.',
        'Cuba' => 'Cuba is an island country in the Caribbean Sea.',
        'Cyprus' => 'Cyprus is an island country in the Eastern Mediterranean.',
        'Czech Republic' => 'The Czech Republic is a landlocked country in Central Europe.',
        'Denmark' => 'Denmark is a Scandinavian country in Northern Europe.',
        'Djibouti' => 'Djibouti is a small country in the Horn of Africa.',
        'Dominica' => 'Dominica is an island country in the Caribbean Sea.',
        'Dominican Republic' => 'The Dominican Republic is a country on the island of Hispaniola in the Caribbean.',
        'Ecuador' => 'Ecuador is a country in South America, known for the Galápagos Islands.',
        'Egypt' => 'Egypt is a country in North Africa known for its ancient civilization and monuments.',
        'El Salvador' => 'El Salvador is the smallest country in Central America.',
        'Equatorial Guinea' => 'Equatorial Guinea is a small country on the west coast of Central Africa.',
        'Eritrea' => 'Eritrea is a country in the Horn of Africa, bordering the Red Sea.',
        'Estonia' => 'Estonia is a small country in Northern Europe, bordered by the Baltic Sea.',
        'Eswatini' => 'Eswatini, formerly Swaziland, is a landlocked country in Southern Africa.',
        'Ethiopia' => 'Ethiopia is a landlocked country in the Horn of Africa.',
        'Fiji' => 'Fiji is an island nation in the South Pacific Ocean.',
        'Finland' => 'Finland is a Nordic country in Northern Europe, known for its lakes and forests.',
        'France' => 'France is a country in Western Europe known for its history, culture, and landmarks.',
        'Gabon' => 'Gabon is a country in Central Africa, bordered by the Atlantic Ocean.',
        'Gambia' => 'Gambia is a small country in West Africa, known for the River Gambia.',
        'Georgia' => 'Georgia is a country at the intersection of Europe and Asia, on the Black Sea.',
        'Germany' => 'Germany is a country in Central Europe known for its rich history and economic power.',
        'Ghana' => 'Ghana is a country in West Africa known for its diverse cultures and natural resources.',
        'Greece' => 'Greece is a country in Southeastern Europe known for its ancient history and islands.',
        'Grenada' => 'Grenada is a Caribbean island country known for its spices and beaches.',
        'Guatemala' => 'Guatemala is a country in Central America, known for its Mayan ruins.',
        'Guinea' => 'Guinea is a country in West Africa known for its mineral resources.',
        'Guinea-Bissau' => 'Guinea-Bissau is a country in West Africa, bordered by Guinea and Senegal.',
        'Guyana' => 'Guyana is a country on the northeastern coast of South America.',
        'Haiti' => 'Haiti is a country on the island of Hispaniola in the Caribbean Sea.',
        'Honduras' => 'Honduras is a country in Central America.',
        'Hungary' => 'Hungary is a landlocked country in Central Europe, known for its culture and architecture.',
        'Iceland' => 'Iceland is a Nordic island country in the North Atlantic, known for its geothermal activity.',
        'India' => 'India is a country in South Asia, known for its diverse cultures, religions, and landscapes.',
        'Indonesia' => 'Indonesia is an archipelago in Southeast Asia, consisting of thousands of islands.',
        'Iran' => 'Iran is a country in Western Asia, known for its ancient civilization.',
        'Iraq' => 'Iraq is a country in Western Asia, known for its rich history and Mesopotamian culture.',
        'Ireland' => 'Ireland is an island nation in the North Atlantic, known for its green landscapes.',
        'Israel' => 'Israel is a country in the Middle East, known for its historical and religious significance.',
        'Italy' => 'Italy is a country in Southern Europe, known for its art, history, and cuisine.',
        'Jamaica' => 'Jamaica is an island country in the Caribbean, known for its music and culture.',
        'Japan' => 'Japan is an island nation in East Asia, known for its technology and culture.',
        'Jordan' => 'Jordan is a country in the Middle East, known for the ancient city of Petra.',
        'Kazakhstan' => 'Kazakhstan is a large landlocked country in Central Asia.',
        'Kenya' => 'Kenya is a country in East Africa, known for its wildlife and landscapes.',
        'Kiribati' => 'Kiribati is a small island country in the central Pacific Ocean.',
        'Korea (North)' => 'North Korea is a country in East Asia, known for its authoritarian regime.',
        'Korea (South)' => 'South Korea is a country in East Asia, known for its technology and culture.',
        'Kuwait' => 'Kuwait is a small country in the Persian Gulf, known for its oil reserves.',
        'Kyrgyzstan' => 'Kyrgyzstan is a landlocked country in Central Asia.',
        'Laos' => 'Laos is a landlocked country in Southeast Asia, known for its mountainous terrain.',
        'Latvia' => 'Latvia is a country in the Baltic region of Northern Europe.',
        'Lebanon' => 'Lebanon is a country in the Middle East, known for its rich history and culture.',
        'Lesotho' => 'Lesotho is a landlocked country in Southern Africa, surrounded by South Africa.',
        'Liberia' => 'Liberia is a country on the west coast of Africa.',
        'Libya' => 'Libya is a country in North Africa, bordered by the Mediterranean Sea.',
        'Liechtenstein' => 'Liechtenstein is a small landlocked country in Central Europe.',
        'Lithuania' => 'Lithuania is a country in the Baltic region of Northern Europe.',
        'Luxembourg' => 'Luxembourg is a small landlocked country in Western Europe.',
        'Madagascar' => 'Madagascar is an island country off the southeastern coast of Africa.',
        'Malawi' => 'Malawi is a landlocked country in southeastern Africa.',
        'Malaysia' => 'Malaysia is a country in Southeast Asia, known for its rainforests and beaches.',
        'Maldives' => 'Maldives is a tropical paradise in the Indian Ocean.',
        'Mali' => 'Mali is a landlocked country in West Africa.',
        'Malta' => 'Malta is a small island country in the Mediterranean Sea.',
        'Marshall Islands' => 'The Marshall Islands is a country of islands in the Pacific Ocean.',
        'Mauritania' => 'Mauritania is a country in West Africa.',
        'Mauritius' => 'Mauritius is an island country in the Indian Ocean.',
        'Mexico' => 'Mexico is a country in North America, known for its rich culture and history.',
        'Micronesia' => 'Micronesia is a region in the Pacific Ocean consisting of many small islands.',
        'Moldova' => 'Moldova is a landlocked country in Eastern Europe.',
        'Monaco' => 'Monaco is a small city-state on the French Riviera in Western Europe.',
        'Mongolia' => 'Mongolia is a landlocked country in East Asia and Central Asia.',
        'Montenegro' => 'Montenegro is a small country in Southeast Europe on the Adriatic Sea.',
        'Morocco' => 'Morocco is a country in North Africa, known for its culture and historic cities.',
        'Mozambique' => 'Mozambique is a country in Southeast Africa, bordered by the Indian Ocean.',
        'Myanmar' => 'Myanmar, formerly Burma, is a country in Southeast Asia.',
        'Namibia' => 'Namibia is a country in Southern Africa, known for its deserts and wildlife.',
        'Nauru' => 'Nauru is a small island country in the Pacific Ocean.',
        'Nepal' => 'Nepal is a landlocked country in South Asia, known for the Himalayas.',
        'Netherlands' => 'The Netherlands is a country in Western Europe known for its flat landscape.',
        'New Zealand' => 'New Zealand is an island country in the South Pacific Ocean.',
        'Nicaragua' => 'Nicaragua is a country in Central America, known for its lakes and volcanoes.',
        'Niger' => 'Niger is a landlocked country in West Africa.',
        'Nigeria' => 'Nigeria is a country in West Africa, known for its diverse cultures and economy.',
        'North Macedonia' => 'North Macedonia is a country in Southeast Europe.',
        'Norway' => 'Norway is a Scandinavian country known for its fjords and natural beauty.',
        'Oman' => 'Oman is a country on the southeastern coast of the Arabian Peninsula.',
        'Pakistan' => 'Pakistan is a country in South Asia, bordered by India and Afghanistan.',
        'Palau' => 'Palau is an island country in the Pacific Ocean.',
        'Panama' => 'Panama is a country in Central America, known for the Panama Canal.',
        'Papua New Guinea' => 'Papua New Guinea is a country in Oceania, known for its diverse cultures.',
        'Paraguay' => 'Paraguay is a landlocked country in South America.',
        'Peru' => 'Peru is a country in South America, known for its ancient Incan civilization.',
        'Philippines' => 'The Philippines is an archipelago in Southeast Asia.',
        'Poland' => 'Poland is a country in Central Europe known for its rich history and culture.',
        'Portugal' => 'Portugal is a country on the Iberian Peninsula in southwestern Europe.',
        'Qatar' => 'Qatar is a small country on the northeastern coast of the Arabian Peninsula.',
        'Romania' => 'Romania is a country in Southeastern Europe, known for its medieval castles.',
        'Russia' => 'Russia is the largest country in the world, spanning Eastern Europe and Northern Asia.',
        'Rwanda' => 'Rwanda is a landlocked country in East-Central Africa.',
        'Saint Kitts and Nevis' => 'Saint Kitts and Nevis is a small island nation in the Caribbean.',
        'Saint Lucia' => 'Saint Lucia is an island country in the Caribbean.',
        'Saint Vincent and the Grenadines' => 'Saint Vincent and the Grenadines is a country in the Caribbean.',
        'Samoa' => 'Samoa is a country in the South Pacific Ocean.',
        'San Marino' => 'San Marino is a landlocked country surrounded by Italy.',
        'Sao Tome and Principe' => 'São Tomé and Príncipe is a small island country in the Gulf of Guinea.',
        'Saudi Arabia' => 'Saudi Arabia is a country in the Middle East, known for its oil reserves.',
        'Senegal' => 'Senegal is a country in West Africa, known for its culture and history.',
        'Serbia' => 'Serbia is a country in Southeast Europe.',
        'Seychelles' => 'Seychelles is an island country in the Indian Ocean.',
        'Sierra Leone' => 'Sierra Leone is a country in West Africa, known for its beaches and rainforests.',
        'Singapore' => 'Singapore is a city-state and global financial hub in Southeast Asia.',
        'Slovakia' => 'Slovakia is a landlocked country in Central Europe.',
        'Slovenia' => 'Slovenia is a country in Southern Central Europe.',
        'Solomon Islands' => 'The Solomon Islands is a country in the South Pacific Ocean.',
        'Somalia' => 'Somalia is a country in the Horn of Africa, bordered by the Indian Ocean.',
        'South Africa' => 'South Africa is a country in Southern Africa, known for its biodiversity and history.',
        'South Sudan' => 'South Sudan is a landlocked country in Northeast Africa.',
        'Spain' => 'Spain is a country in Southwestern Europe, known for its rich culture and landmarks.',
        'Sri Lanka' => 'Sri Lanka is an island country in South Asia, known for its beaches and wildlife.',
        'Sudan' => 'Sudan is a country in North Africa, bordered by Egypt and the Red Sea.',
        'Suriname' => 'Suriname is a country in South America, known for its Dutch heritage.',
        'Sweden' => 'Sweden is a Nordic country in Northern Europe.',
        'Switzerland' => 'Switzerland is a landlocked country in Central Europe, known for its mountains.',
        'Syria' => 'Syria is a country in the Middle East, known for its ancient history.',
        'Taiwan' => 'Taiwan is an island country in East Asia, known for its technology.',
        'Tajikistan' => 'Tajikistan is a landlocked country in Central Asia.',
        'Tanzania' => 'Tanzania is a country in East Africa, home to Mount Kilimanjaro and the Serengeti.',
        'Thailand' => 'Thailand is a country in Southeast Asia, known for its beaches and temples.',
        'Togo' => 'Togo is a country in West Africa.',
        'Tonga' => 'Tonga is a Polynesian kingdom in the South Pacific.',
        'Trinidad and Tobago' => 'Trinidad and Tobago is a twin-island country in the Caribbean.',
        'Tunisia' => 'Tunisia is a country in North Africa, known for its Mediterranean beaches.',
        'Turkey' => 'Turkey is a country that straddles Europe and Asia, known for its rich history.',
        'Turkmenistan' => 'Turkmenistan is a country in Central Asia.',
        'Tuvalu' => 'Tuvalu is a small island country in the Pacific Ocean.',
        'Uganda' => 'Uganda is a landlocked country in East Africa.',
        'Ukraine' => 'Ukraine is a country in Eastern Europe, known for its agriculture and history.',
        'United Arab Emirates' => 'The UAE is a country in the Middle East, known for its modern cities and oil.',
        'United Kingdom' => 'The United Kingdom is a country in Europe, comprising England, Scotland, Wales, and Northern Ireland.',
        'United States' => 'The United States is a country in North America, known for its diverse culture and global influence.',
        'Uruguay' => 'Uruguay is a country in South America, known for its beaches and soccer.',
        'Uzbekistan' => 'Uzbekistan is a country in Central Asia, known for its Silk Road history.',
        'Vanuatu' => 'Vanuatu is an island country in the South Pacific Ocean.',
        'Vatican City' => 'Vatican City is an independent city-state and the spiritual center of the Roman Catholic Church.',
        'Venezuela' => 'Venezuela is a country in South America, known for its oil reserves and natural beauty.',
        'Vietnam' => 'Vietnam is a country in Southeast Asia, known for its history and cuisine.',
        'Yemen' => 'Yemen is a country on the Arabian Peninsula, known for its ancient history.',
        'Zambia' => 'Zambia is a landlocked country in Southern Africa.',
        'Zimbabwe' => 'Zimbabwe is a landlocked country in Southern Africa, known for its wildlife and history.'
        // Add other countries as needed
    );

    foreach ( $countries as $country => $description ) {
        if ( ! term_exists( $country, 'country' ) ) {
            wp_insert_term( $country, 'country', array( 'description' => $description ) );
        }
    }
}

// add_action('init', 'add_countries_with_descriptions'); // Run this once manually then comment it


function update_country_descriptions() {
    $countries = array(
        'India' => 'Updated description for India.',
        'United States' => 'Updated description for the USA.',
        // Add others...
    );

    foreach ($countries as $country => $description) {
        $term = get_term_by('name', $country, 'country');
        if ($term) {
            wp_update_term($term->term_id, 'country', array('description' => $description));
        }
    }
}

// add_action('init', 'update_country_descriptions'); // Run this once manually then comment it

